language: rust
os: linux
dist: focal

branches:
  only:
    - master

install:
  - sudo apt-get install ccache
  - rustup component add clippy

script:
  - ./.ci/build.sh $FEATURES

jobs:
  include:
    - name: "Stable x86-64"
      rust: stable

    - name: "Stable arm64"
      arch: arm64
      rust: stable

    - name: "Stable arm64 vendored"
      arch: arm64
      rust: stable
      env:
       - FEATURES="vendored"

    - name: "Stable ppc64le"
      arch: ppc64le
      rust: stable

    - name: "Stable s390x"
      arch: s390x
      rust: stable

    - name: "Beta x86-64"
      rust: beta

    - name: "Nightly ppc64le"
      arch: ppc64le
      rust: nightly

    - name: "Nightly arm64 no_std"
      arch: arm64
      rust: nightly
      env:
       - FEATURES="no-std"

cache:
  directories:
    - $HOME/.ccache
