[package]
name = "botan-sys"
version = "0.8.1"
authors = ["Jack Lloyd <jack@randombit.net>"]
links = "botan-2"
build = "build.rs"
description = "FFI wrapper for Botan cryptography library"
license = "MIT"
homepage = "https://botan.randombit.net/"
repository = "https://github.com/randombit/botan-rs"
documentation = "https://docs.rs/botan-sys"
readme = "README.md"
categories = [ "cryptography", "external-ffi-bindings", "no-std" ]

[features]
default = []
no-std = []
vendored = ["botan-src"]

[dependencies]
cty = { version = "0.2" }

[build-dependencies]
botan-src = { version = "0.21702", optional = true, path = "../botan-src" }
