[package]
name = "botan-sys"
version = "0.1.1"
authors = ["Jack Lloyd <jack@randombit.net>"]
links = "botan-2"
build = "build.rs"
description = "FFI wrapper for Botan cryptography library"
license = "MIT"
homepage = "https://botan.randombit.net/"
categories = [ "cryptography" ]

[badges]
travis-ci = { repository = "randombit/botan-rs" }

[badges.maintenance]
status = "experimental"

[dependencies]
