[package]
name = "botan"
version = "0.1.3"
authors = ["Jack Lloyd <jack@randombit.net>"]
description = "Rust wrapper for Botan cryptography library"
license = "MIT"
homepage = "https://botan.randombit.net/"
keywords = [ "crypto" ]
categories = [ "cryptography", "api-bindings" ]

[badges]
travis-ci = { repository = "randombit/botan-rs" }

[badges.maintenance]
status = "experimental"

[dependencies]
botan-sys = { version = "0.1.3", path = "../botan-sys" }
