[package]
name = "botan"
version = "0.1.5"
authors = ["Jack Lloyd <jack@randombit.net>"]
description = "Rust wrapper for Botan cryptography library"
license = "MIT"
homepage = "https://botan.randombit.net/"
repository = "https://github.com/randombit/botan-rs"
documentation = "https://docs.rs/botan"
keywords = [ "crypto" ]
categories = [ "cryptography", "api-bindings" ]

[badges]
travis-ci = { repository = "randombit/botan-rs" }

[badges.maintenance]
status = "actively-developed"

[dependencies]
botan-sys = { version = "0.1.5", path = "../botan-sys" }
